### ISSUE TITLE
Fill user.email value in example

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/flutter-passkeys#35]
**Background**
Currently, in the example, we use the email address as the "name" and leave the email field blank when creating a new user, as there is no username field in the example.

**TODO**
Can we please add the email also to the corresponding email address field in the backend.

**Comment by incorbador** [comment]
Username and email are both set (to the same value to keep the example simple). The email is just not returned because it has not been verified (in that case the Corbado backend will not include the email as part of the JWT). 

I verified the email for one of the accounts I created in the example => the email is shown then.

**Comment by incorbador** [comment]
I'll close this issue here for now then :)
