### ISSUE TITLE
How to implement conditional UI?

### ISSUE THREAD

**Issue by InAnadea** [corbado/flutter-passkeys#54]
Is there any example of conditional UI implementation?

**Comment by vincentdelitz** [comment]
Hey @InAnadea, our native app example for our developer panel implements conditional UI: https://github.com/corbado/corbado-native-app

**Comment by InAnadea** [comment]
Thank you! But that link directs me to a 404 page. Maybe I need additional access to this page?

**Comment by vincentdelitz** [comment]
sorry wrong link, here is the same repository / example: https://github.com/corbado/example-passkeys-flutter

**Comment by InAnadea** [comment]
Thanks! I've implemented authentication without username/email on custom replying server (just omitting user info in passkey request). But still don't understand how works 'webauthn' autocomplete key in the browser. 
For now I create request without email/username and use the same flow for finishing signing in (with manual sign in button). But how works autocompletion in browser without any additional button. 

<img width="517" alt="Screenshot 2024-03-13 at 15 47 54" src="https://github.com/corbado/flutter-passkeys/assets/93736963/69f8e899-3640-4983-be05-5335ea08e5be">

**Comment by incorbador** [comment]
Hey @InAnadea.
Just so that I get you right: You want to understand how you can use flutter-passkeys to build a web-app with conditional UI, right? 

In that case, we have also running examples in this repo. The simplest one (the one for the passkeys package) is deployed here: https://passkeys.flutter.corbado.io
You can create an account there and the trigger a conditional UI login afterwards. The code for the example can be found in this repo's packages/passkeys/passkeys/example/lib. Feel free to check it out.

![image](https://github.com/corbado/flutter-passkeys/assets/134682658/77cf9cc0-0931-4c57-bc58-8066c12a7c42)

**Comment by InAnadea** [comment]
Thanks! Thats what I need!
