### ISSUE TITLE
androidx.credentials.TYPE_SECURITY_ERROR when using example app

### ISSUE THREAD

**Issue by briancorbin** [corbado/flutter-passkeys#60]
Hey there, so I'm running in to an issue when running the example passkey native app in the repo on an android simulator. This is also the same as the error returned in my own application. Steps to reproduce:

1. From packages/passkeys/passkeys directory, run `melos run example-passkeys-native` as instructed in the README
2. Type in email address in the email address section
3. click sign up

Returns error after a moment saying TYPE_SECURITY_ERROR The incoming request cannot be validated.

I have not modified any parts of the example application.

**Comment by briancorbin** [comment]
This happens both on physical device and on emulator

**Comment by eimjustas** [comment]
Having exactly the same issue on Android device.

OnePlus9, Android 14

**Comment by incorbador** [comment]
@briancorbin @eimjustas 
Hey guys, thanks for bringing this up. We fixed it now => examples should work again now.

In case you are interested about the root cause of the error:
There was a misconfiguration on our side. The relying party ID got changed from flutter.corbado.io to corbado.io. This meant that Android (but also iOS devices) could no longer fetch assetlinks.json (or apple-app-site-association) files and the OS (in that case Android throws an exception).
