### ISSUE TITLE
Error in web application when running build_runner with corbado_auth package

### ISSUE THREAD

**Issue by Kuhney** [corbado/flutter-passkeys#63]
To generate code for other packages I do a build_runner build before starting the app, but when I do this I get a white page and following error message
`Rejecting promise with error: TypeError: Cannot read properties of undefined (reading 'init')`

To replicate this problem, have the following setup:
New blank Flutter (v3.19.6) project
add `corbado_auth: ^2.0.7` dependency
add `build_runner: ^2.4.9` dev-dependency
run `dart run build_runner build`
try to start the app in a web application

**Comment by incorbador** [comment]
Hello @Kuhney. This problem can be fixed by including the following code in your /web/index.html.

`  <script src="https://github.com/corbado/flutter-passkeys/releases/download/2.0.0-dev.1/bundle.js" type="application/javascript"></script>
`

For reference you can take a look at our example for corbado_auth: https://github.com/corbado/flutter-passkeys/blob/main/packages/corbado_auth/example/web/index.html

I'll update the according README file to make this a bit more clear as I understand that this is not obvious. Please notify me if your problem was fixed (then I will close the issue).

**Comment by Kuhney** [comment]
Thank you for your quick answer @incorbador.
Yes that was the fix!
